# App:
#     resource: ../../src/Controller/
#     type: annotation

Game:
    resource: ../../src/Game/Controller/
    type: annotation

Jugadores:
    resource: ../../src/Jugadores/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
