# index:
#    path: /
#    controller: App\Controller\DefaultController::index


jugadores:
   path: /jugadores/
   controller: App\Jugadores\Controller\JugadoresController::index


game:
   path: /game/
   controller: App\Game\Controller\GameController::index
